services:
  - type: web
    name: ai-trends-ai
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: OPENAI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
    autoDeploy: true